---
- name: Restart haproxy service on haproxy Cluster 
  hosts: haproxy
  sudo: yes
  sudo_user: root
  
  tasks:
  - name: stop the haproxy compose file
    command: docker-compose -f /arris/compose/haproxy-compose.yml stop
    async: 60
    poll: 10   
     
  - name: rm haproxy 
    command: docker-compose -f /arris/compose/haproxy-compose.yml rm --force
    async: 60
    poll: 10   
     
  - name: start the compose file 
    command: docker-compose -f /arris/compose/haproxy-compose.yml up -d
   