lbaasapi:
  image: dockerrepo:5000/arrs/arrs-cloud-base-lbaas-api:1.0.0.1
  stdin_open: true
  tty: true
  restart: always
  privileged: true
  log_driver: "json-file"
  log_opt:
   max-size: "100m"
   max-file: "10"
  ports:
  - "9102:9102"
  environment:
  - LISTEN_PORT=9102
  volumes:
  - /var/opt/lbaas_api/logs:/opt/lbaas_api/logs
  - /opt/etcd/config:/opt/etcd/config
  
lbaasapiapp:
  image: dockerrepo:5000/arrs/arrs-cloud-base-lbaas-api-app-monitor:1.0.0.1
  stdin_open: true
  tty: true
  restart: always
  privileged: true
  ports:
   - "7608:7608"
  log_driver: "json-file"
  log_opt:
   max-size: "100m"
   max-file: "10"   
  environment:
   LISTEN_PORT: 7608
   APP_OBSERVER_PORT: 8977
   HOST_IP: HOST_IP_MACRO
   HOST_NAME: HOST_NAME_MACRO
  volumes:
   - /usr/sbin:/usr/local/sbin
   - /var/log/app_monitor/lbaas_api:/tmp
   - /var/opt/app-monitor-lbaas-api/status_monitor/logs:/opt/status_monitor/logs

appObserverLbaasApi:
  image: dockerrepo:5000/arrs/arrs-cloud-base-app-observer:2.0.0.3
  restart: always
  privileged: true
  ports:
   - "8975:8975"
   - "8977:8977"
  log_driver: "json-file"
  log_opt:
   max-size: "100m"
   max-file: "10"  
  environment:
   SECURE_PORT: 8975
   NON_SECURE_PORT: 8977
   PRODUCT_NAME: ACP-LBAAS-API
   APP_WEBSERVICE_FQDN: HOST_IP_MACRO
   APP_WEBSERVICE_PORT: 7608
  volumes:
   - /var/opt/app-observer-lbaas-api/config:/opt/app-observer/conf/external
   - /var/opt/app-observer-lbaas-api/logs:/opt/app-observer/logs
  
keymanager:
  image: dockerrepo:5000/arrs/arrs-cloud-base-keymanager:1.0.0.9
  stdin_open: true
  tty: true
  restart: always
  privileged: true
  log_driver: "json-file"
  log_opt:
   max-size: "100m"
   max-file: "10"
  environment:
  - HOST_IP=HOST_IP_MACRO
  - HOST_NAME=HOST_NAME_MACRO
  volumes:
   - /var/log:/tmp
   - /opt/etcd/config:/opt/etcd/config

logstashforwarder:
  image: dockerrepo:5000/arrs/arrs-cloud-base-logstash-forwarder:2.0.0.4
  restart: always
  privileged: true
  log_driver: "json-file"
  log_opt:
   max-size: "100m"
   max-file: "10"  
  environment:
   LS_HEAP_SIZE: 1g
   CA_CERT_LOCATION: /etc/elk-keys/ca.pem
   ES_HOST: ELK_DNSNAME_MACRO
   NODE_NAME: HOST_IP_MACRO
  volumes:
   - /var/opt/logstash-forwarder/log:/var/log/supervisor
   - /var/opt/logstash-forwarder/conf:/etc/logstash-forwarder
   - /var/opt/logstash-forwarder/keys:/etc/elk-keys
   - /etc/localtime:/etc/localtime:ro   
   - /var/opt/lbaas_api/logs:/opt/lbaas_api/logs
   
   
   
